flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.1.0.0
- authenticate-oauth-1.5.1.2
- hasktags-0.68.2
- primitive-0.6.2.0
- vector-0.12.0.0
- wreq-0.5.0.0
- xml-conduit-1.4.0.4
resolver: lts-8.0
